### ISSUE TITLE
Look into creating labels layers dynamically

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tilequeue#21]
Because we have the whole geometry for features during processing, we can calculate the centroid in memory, and dynamically generate any labels layers.

**Comment by zerebubuth** [comment]
This should be pretty easy after #22, or something like it, lands.

**Comment by nvkelso** [comment]
See also: 

* https://github.com/mapzen/vector-datasource/issues/226

**Comment by nvkelso** [comment]
Before adding the new `label_position` points, we need to test if the shape is a `Polygon` or a `MultiPolygon`, else we'll get duplicate points and weird centroids for lines.

**Comment by nvkelso** [comment]
I'm seeing new `label_positions` in the `building` layer, good! But I'm also seeing placements that don't have a `name` property, which is weird. 

http://vector.dev.mapzen.com/osm/all/14/2619/6334.topojson?api_key=vector-tiles-HqUVidw

In rare situations on sports `pitch` landuse when the name is empty but `sport` is set, I can see including the label position still. But in almost all other cases we should just drop this before exporting. 

Speaking of sport pitches, these don't seem to be getting label_positions now?

http://vector.mapzen.com/osm/all/16/10467/25333.topojson?api_key=vector-tiles-HqUVidw

**Comment by rmarianski** [comment]
> But I'm also seeing placements that don't have a name property, which is weird.

Ah, that's an oversight on my part. In the labels layer we used to have a condition to only include the feature if the name was not null, but I didn't port that logic over when auto-generating the label features. Should be easy to add in.

> Speaking of sport pitches, these don't seem to be getting label_positions now?

That is odd. Is it possible that the centroid is just in an adjacent tile?

**Comment by nvkelso** [comment]
Here's a sports pitch that **is** working as expected:

http://vector.dev.mapzen.com/osm/all/16/10481/25328.topojson?api_key=vector-tiles-HqUVidw

We'll want to preserve them (even without the name filled in) so we can draw sport icons on the pitch :)

**Comment by rmarianski** [comment]
Should this be left as is then? Or should there be special logic applied if the `sport` tag is present?

**Comment by nvkelso** [comment]
Looks like `sport=*` is combined to any number of other tags:

* https://taginfo.openstreetmap.org/keys/sport#combinations

* if `name` doesn't exist but  `sport`  does, keep it (export as `label_position`)
* if `name` doesn't exist and `sport`  doesn't, don't keep it (don't export as `label_position`)

**Comment by nvkelso** [comment]
Representative points are working, thanks!

**Comment by nvkelso** [comment]
Unnamed sports pitches are coming thru :)
