### ISSUE TITLE
Use a date prefix on the s3 bucket

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tilequeue#31]
When we change buckets for storage, we have to coordinate the changes across a few different places. It would be a little bit easier if the bucket always stayed the same, and the data was just put into date prefixes.

**Comment by zerebubuth** [comment]
Which date?

Might this be something where the version number (of the software / queries) would be helpful?

**Comment by rmarianski** [comment]
I was thinking date of deployment, which is how we name the buckets now. But it could be any version number.

This is the sort of thing that would change less frequently than the software/query changes; we really only change it when we don't want to show stale data in dev, or when we need to atomically switch the tilesets in prod.

**Comment by rmarianski** [comment]
Additionally, we'll want to consider following s3 best practices for our object key names. This effectively boils down to adding a hash prefix to the name. Thanks @zerebubuth!

http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

For this to work though, we'll need to ensure that fastly can manipulate the urls accordingly. Some research needs to be done here to verify, although at first glance these functions look promising:

https://docs.fastly.com/guides/vcl/cryptographic-and-hashing-related-vcl-functions

**Comment by nvkelso** [comment]
@rmarianski, how should we QA this one?

**Comment by rmarianski** [comment]
The tiles should still be loading at the same rate. On the back end the s3 bucket will have objects sitting in a different location.

**Comment by nvkelso** [comment]
TileBRB: This is deployed in dev. That everything is still working via S3 means this is working?

**Comment by nvkelso** [comment]
With today's new dev deploy, I see a new dir in the dev S3 bucket with today’s date on it, and the dated dir is there there, and no new garbled root dirs so that verifies this issue.
