### ISSUE TITLE
Investigate cause of segfaults

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tilequeue#54]
We're seeing some segfaults in our logs. There's some logging in place now to start tracking when these happen, but we're not getting very much information from them at the moment. Each occurrence does seem to share the same library offset in libgeos though.

    Nov 16 22:19:20 tilequeue24 kernel: [2196859.797264] tilequeue[17743]: segfault at 0 ip 00007f09b1905f80 sp 00007ffdfebf8d18 error 4 in libgeos-3.4.2.so[7f09b1831000+176000]

**Comment by zerebubuth** [comment]
Ooops, this would have been a more appropriate place to write [this comment](https://github.com/mapzen/chef-mapzen_tilequeue/pull/19#issuecomment-157371074).

**Comment by rmarianski** [comment]
Great idea! I'll look into what it takes to make this happen for the future.

Luckily though, getting down to the bottom of the queue ended up revealing a few tiles that reliably reproduce the issue, at least on a production machine.

* 13/4241/2797
* 15/9177/11925
* 15/16963/11189
* 15/16964/11189
* 15/16964/11190

**Comment by zerebubuth** [comment]
All but one of those tiles are near [Apach, France](http://www.openstreetmap.org/#map=15/49.4586/6.3745), which is a pretty strong indication that there's a bit of geometry there which is causing GEOS to choke. More specifically, it seems to be around the railway station (but it's along the river, too, so no clues yet as to which bit of geometry might be causing it). But if we can reproduce it, we can debug it :smile:

**Comment by zerebubuth** [comment]
Are we seeing any more segfaults in production after fixing that snapped geoms issue?

**Comment by rmarianski** [comment]
I didn't push out a fix to production for this yet. There's a couple of updates to fix other issues too, maybe it makes sense to roll all those out at once.
