### ISSUE TITLE
500 error from a VTM tile

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/tilequeue#55]
This particular tile appears to reproducibly respond with a 500 error:

`curl -o /dev/null -v "http://vector.mapzen.com/osm/buildings/16/60289/39333.vtm"`

Needs looking into at some point.

**Comment by rmarianski** [comment]
2015-11-23_18:08:39.71689 Error handling request for /buildings/16/60289/39333.vtm: Traceback (most recent call last): |   File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 133, in __
call__    response = self.handle_request(request) |   File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 191, in handle_request    bounds_merc, bounds_wgs84) |   File "/usr/local/lib/p
ython2.7/dist-packages/tilequeue/format.py", line 36, in format_tile    bounds_wgs84) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/format.py", line 84, in format_vtm    vtm_merge(fp, feature_lay
ers, coord) |   File "/usr/local/lib/python2.7/dist-packages/TileStache/Goodies/VecTiles/oscimap.py", line 45, in merge    tile.addFeatures(layer['features'], coord, layer['name']) |   File "/usr/local/lib/py
thon2.7/dist-packages/TileStache/Goodies/VecTiles/oscimap.py", line 87, in addFeatures    self.addFeature(feature, coord, this_layer) |   File "/usr/local/lib/python2.7/dist-packages/TileStache/Goodies/VecTil
es/oscimap.py", line 109, in addFeature    tag = str(k), str(v) | UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 13: ordinal not in range(128)
