### ISSUE TITLE
Be robust to WOF neighbourhood (git access) HTTP errors

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/tilequeue#60]
For example:

```
2015-12-28 12:11:12,342 - wof_process_neighbourhoods - ERROR - Neighbourhood failure for 85887467: 'Invalid response 504 for http://whosonfirst.mapzen.com/data/858/874/67/85887467.geojson' - u''
```

504s (and other 5xx errors) are just going to happen sometimes because noise in the intertubes. So we should back off and retry a few times before returning an error. It looks like this [might be supported](http://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request) by the `requests` library we're using.

**Comment by zerebubuth** [comment]
Got a unicorn (502) from Github, which caused another false alarm. Seems likely that it wouldn't have occurred twice, so retrying would have helped (I'm assuming Github chose a unicorn for this error because it should never exist).

**Comment by nvkelso** [comment]
We keep getting pager duty alerts about this, pulling this into v0.7

**Comment by nvkelso** [comment]
Let's take this to `dev` first (right now we get alerts in both `dev` and `prod`), and if we only get alerts on `prod` in the future, this is verified as working on `dev` and we can take to `prod`.

**Comment by nvkelso** [comment]
Let's pair testing with a few neighbourhood edits in WOF to improve likelihood this will be triggered.

**Comment by nvkelso** [comment]
Some neighbourhoods have been edited, those came thru well. Others were manually expired on the server as a test, and those all fetched correctly. We suspect this only would be trigged when Github is having a service issue on their end, e.g.: "exception percentage" spikes on https://status.github.com/. This causes no regression on our end, and should guard against Github funk. Let's take this live.
