### ISSUE TITLE
Push expiry notifications when storing

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/tilequeue#67]
When storing a tile, push a notification on some channel.

That's very vague, but intentionally so. What has been talked about is pushing the tile coordinate `z/x/y` as a [Surrogate-Key](https://www.fastly.com/blog/surrogate-keys-part-1) to Fastly after all the formats / versions of a tile were written to S3. Note that this would also mean setting [special headers on S3](https://docs.fastly.com/guides/purging/setting-surrogate-key-headers-for-amazon-s3-origins) for all formats / versions of a tile when it was first written.

Rather than having the tilequeue process push the (soft) purge directly to Fastly, it might be worth pushing it to a pub-sub or SQS channel for some other process to run asynchronously. Another alternative would be triggering actions directly from S3 using [AWS lambda](http://docs.aws.amazon.com/lambda/latest/dg/welcome.html).

**Comment by rmarianski** [comment]
Related https://github.com/mapzen/tile-tasks/issues/11

**Comment by zerebubuth** [comment]
We're expiring about 121,000 tiles per hour, but there are [rate limits](https://docs.fastly.com/api/#rate-limiting) which make it less feasible.

Closing in favour of mapzen/tile-tasks#11.
