### ISSUE TITLE
Pass context object to post-process functions

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/tilequeue#70]
At the moment, we pass the following parameters to the post-process functions:

* `feature_layers` - the `list` of layers,
* `zoom` - an `int` for the zoom level,
* `**params` - a `dict` of parameters which are mostly from the config file, but `bounds` comes automatically from the calling function.

The addition of `bounds` in #69 was a pretty egregious hack, and a better (but much larger) change would be to pass a context object containing all the context of the request. Since layers are often looked up by name, then it would make it easier if the layers, zoom and bounds all came from the context object and the configuration params were the only other parameter.

How does that sound? Anything else we ought to be taking into account? Best to pass a `NamedTuple` to avoid cross-module includes, or should it be a full object with methods (e.g: to abstract named layer lookup)?

**Comment by rmarianski** [comment]
:+1: 

I'd prefer it to just be a dumb data bag kind of object. Not sure I follow the cross-module includes concern, but a `NamedTuple` sounds fine to me. And a dictionary object that has named lookup for the individual layers would simplify some of the transforms. I guess that means this context would need to get mutated though if layers are added/removed in the transforms, but I think it's fine for the transforms to be aware of this. We could add a helper function when we alter the layers if we were worried about consistency in the transforms.

Don't think any of the post process functions need this, but if we're willing to scope creep a little bit here we can add in more pieces that some of the other formatting transforms use, and we can just pass this context around everywhere. OTOMH padded vs unpadded bounds, maybe as shapely objects to make it useful for intersection checks, the bounds in lnglat, the original coordinate, and anything else that is calculated on demand.
