### ISSUE TITLE
Delegate quantization to mapbox-vector-tile library

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tilequeue#82]
The mapbox-vector-tile library has the option to quantize coordinates while encoding now. Instead of it being done in tilequeue before passing it to the formatter, it should just be delegated to mapbox-vector-tile to avoid having multiple implementations.

**Comment by nvkelso** [comment]
Would the formatter also enforce topological correctness on the output geoms to meet v2 MVT spec?

**Comment by rmarianski** [comment]
It would be the responsibility of the mapbox-vector-tile library.

**Comment by nvkelso** [comment]
@zerebubuth Can you confirm this is working as expected on dev and will also on prod?

**Comment by nvkelso** [comment]
Over to @rmarianski as Monday is a holiday in the UK for Matt.

**Comment by nvkelso** [comment]
@rmarianski see https://github.com/mapzen/TileStache/commit/73af54bd19a38cf429591c88cc8dbd64b122936e#commitcomment-17314785

**Comment by rmarianski** [comment]
Verified that the updated code has been deployed, and that it loads in tangram.
